s.boot;
FreqScope.new;

// Physical modeling originally one using the finite difference approximation of the wave equation by Hiller & Ruiz in 1971. Then, Karplus-Strong algorithm turned into digital waveguide synthesis (Julian Smith). See https://ccrma.stanford.edu/~jos/swgt/swgt.html . Most patents are currently owned by Yamaha or Stanford.
// Cool paper on derivation of finite difference method in sound synthesis http://math.aalto.fi/~ksalo2/akusem/sem_FDM.pdf


